<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>cl.duoc.cloud</groupId>
    <artifactId>bff-cloud-parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>bff-cloud-parent</name>
    <description>Ecosistema de Microservicios Bancarios BFF con Spring Cloud y Netflix Eureka (Semana 6 - PBY2203)</description>

    <modules>
        <module>config-server</module>
        <module>eureka-server</module>
        <module>bff-web</module>
        <module>bff-mobile</module>
        <module>bff-atm</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>
</project>
